packages:
  - block
  - kind
  - model
  - test
  - ui
  - workflow
catalog:
  "@platforma-sdk/model": 1.82.0
  "@platforma-sdk/ui-vue": 1.82.1
  "@milaboratories/graph-maker": 1.4.8
  "@platforma-sdk/workflow-tengo": 6.8.2
  "@platforma-sdk/block-kind": 1.1.0
  "@platforma-sdk/test": 1.82.4
  "@platforma-sdk/block-tools": 2.14.3
  "@platforma-sdk/tengo-builder": 4.0.23
  "@platforma-sdk/package-builder": 3.15.0
  "@milaboratories/ts-builder": 1.7.0
  "@milaboratories/ts-configs": 1.4.0
  "@milaboratories/helpers": 1.14.5
  typescript: ~5.9.3
  turbo: ~2.8.11
  shx: ~0.4.0
  "@changesets/cli": ~2.29.8
  vitest: ~4.0.18
  vue: 3.5.24
